
siteTitle = "Seasonstar' s Blog"
siteDescr = "Love is life. And if you miss love, you miss life."

authorName = "Shawn Tang"

linkTwitter  = "https://twitter.com/seasonskyr"
linkGithub 	 = "https://github.com/seasonstar"
linkWeibo 	 = "http://weibo.com/234323550"
linkEmail 	 = "seasonstar@126.com"
linkRss 	 = "/feed.xml"

linkPrefix = "/react-brief/blog"
